[package]
name = "everybody_codes"
version = "2025.1.0"
authors = ["Charles Pigott <charlespigott@googlemail.com>"]
edition = "2024"

[dependencies]
itertools = "0.14.0"
memoise = "0.3.2"
fixedbitset = "0.5.7"
rustc-hash = "2.0.0"

[profile.release]
debug = true
